version: "3.4"

services:
  app:
    build:
      context: .
      args:
        BUILD_ARGUMENT_ENV: prod
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: ogrine-rates_server
    restart: always
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=14
      REQUEST_OGRINE_FETCH_URL: https://www.dofus.com/fr/achat-kamas/cours-kama-ogrines
      REQUEST_HEADER_USER_AGENT: "Mozilla/5.0"
    ports:
      - 8000:80
    depends_on:
      - database
    networks:
      - internal

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - internal
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  internal:
